

## + ======================================================= 
## +               DEFAULT SET UP FOR TESTS
## + ======================================================= 
@API_HostAddress = http://localhost:5000

@AuthUrl = {{API_HostAddress}}/api/v1/auth
@Product_API = {{API_HostAddress}}/api/v1/products

@ContentType = application/json

### 1. Login User (Obtain JWT Token)
# @name login
POST {{AuthUrl}}/login
Content-Type: {{ContentType}}

{
  "email": "admin@example.com",
  "password": "1234"
}

### 3. Store Tokens for Authentication Flow
@accessToken = {{login.response.body.data.accessToken}}
@refreshToken = {{login.response.body.data.refreshToken}}
@userId = {{login.response.body.data.user.id}}


## + ======================================================= 
## +                Products ENDPOINTS (SUCCESS)
## + ======================================================= 

### 1. Obtener todos los productos (Lista inicial)
GET {{Product_API}}
Accept: application/json
Authorization: Bearer {{accessToken}}


### 2. Crear un nuevo producto con variantes
# @name createProduct
POST {{Product_API}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Teclado Mecánico RGB",
  "description": "Teclado con switches red y retroiluminación RGB",
  "categoryId": null,
  "subcategoryId": null,
  "brandId": null,
  "variants": [
    {
      "sku": "KEY-RGB-BLK",
      "priceArs": 85500.00,
      "comparisonPriceArs": 95000.00,
      "discountArs": 9500,
      "stock": 15,
      "size": "Standard 100%",
      "color": "Negro",
      "hexColor": "#000000"
    },
    {
      "sku": "KEY-RGB-WHT",
      "priceArs": 88000.00,
      "comparisonPriceArs": null,
      "discountArs": 0,
      "stock": 10,
      "size": "Standard 100%",
      "color": "Blanco",
      "hexColor": "#FFFFFF"
    }
  ]
}


### 3. Obtener un producto por ID (Usando variable de la respuesta previa)
# Si tu editor no soporta la variable automática, reemplazá el ID manualmente
@createdProductId = {{createProduct.response.body.id}}

GET {{Product_API}}/{{createdProductId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET BY ID

GET {{Product_API}}/1
Accept: application/json
Authorization: Bearer {{accessToken}}


###

GET {{Product_API}}/1/variants
Accept: application/json
Authorization: Bearer {{accessToken}}

### 4. Actualizar un producto existente
PUT {{Product_API}}/{{createdProductId}}
Content-Type: application/json

{
  "name": "Teclado Mecánico RGB Pro",
  "description": "Teclado con switches red, retroiluminación RGB y reposamuñecas",
  "price": 99.99,
  "stock": 20
}

###

### 5. Eliminar un producto
DELETE {{Product_API}}/{{createdProductId}}
Accept: application/json

###